### ISSUE TITLE
Ctrl+Left and Ctrl+Right are hijacked by the app

### ISSUE THREAD

**Issue by endolith** [jackschedel/gpt.koaladev.io#101]
If I try to move my cursor to a previous word by using Ctrl+Arrow key, it changes documents/chats??   Please don't hijack basic keyboard shortcuts.

**Comment by endolith** [comment]
Honestly this is absolutely infuriating.  You must not use this keyboard shortcut?  Every time I try to move my cursor around while editing a response, it tabs to another conversation and loses what I was typing.  It catches me by surprise every time because using Ctrl to navigate the cursor around words is second nature.  It happens even in the Windows app.

**Comment by jackschedel** [comment]
Sorry about that, I forgot that this would be a conflicting keybind on Windows. On Mac, moving between words uses Option rather than Ctrl. This is fixed in #102, which makes the keybind mac-only. Windows users will still be able to navigate back/forward with their mouse buttons or with the buttons on the top bar.
