### ISSUE TITLE
fix Whisper transcription on website version not working - RecordRTC is destroyed

### ISSUE THREAD

**Issue by jackschedel** [jackschedel/gpt.koaladev.io#66]
**(Whisper is currently disabled on the website because it doesn't work properly. Remove the `isElectron() && ` on line 266 of EditView.tsx to enable it on the website.)**

Electron:
![image](https://github.com/jackschedel/KoalaClient/assets/26682594/f797b99b-d91f-45c0-8197-cb58a7305160)

Website:
![image](https://github.com/jackschedel/KoalaClient/assets/26682594/23584fb8-2e28-4a39-982d-4525c4df02af)

**Comment by jackschedel** [comment]
this has the same issue on `yarn electron`, but not the built version. Strange.

**Comment by HritikR** [comment]
@jackschedel This issue is because of vite dependency optimization. `lamejs` (CJS dependency used by useWhisper)  is being excluded.
This issue only exists on dev server. Production server is working as expected.

Should I create a pull request to fix this in the dev server?
This will also fix `yarn electron`

**Comment by jackschedel** [comment]
@HritikR that would be amazing, thanks.

**Comment by jackschedel** [comment]
fixed in #98 
thanks Hritik!
