### ISSUE TITLE
Inconsistent Chat Title Naming Behaviour on Creating New Chat

### ISSUE THREAD

**Issue by HritikR** [jackschedel/gpt.koaladev.io#96]
Steps to Reproduce:
- Click on the "New Chat" button without sending any messages in the existing chat.
- Observe that the existing chat is renamed to "New Chat 1."
- Repeat steps 2 and 3, and note that subsequent existing chats are renamed incrementally (e.g., "New Chat 2," "New Chat 3," etc.).
- Rename the chat to anything and send a message
- Click on the "New Chat"

https://github.com/jackschedel/KoalaClient/assets/35923605/74eb271b-8c77-498e-afd9-171c04c84fed

**Comment by jackschedel** [comment]
Hi, this is due to a QoL change introduced in v2.0.6 that hides empty chats in the side menu (unless it is the current chat) to reduce clutter. This is the expected behavior, as deleting puts you back to your previous chat, which was hidden, and is then unhidden as it is the current one.

I might rework it to instead fully clear empty chats from the chat data on program init instead to avoid this strange behavior.
